name: Windows Build + Test Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: Build
        run: |
          cmake -G "NMake Makefiles" .
          nmake
      - name: Test Run
        run: ./TestTaskTest.exe
