name: Windows Build + Test Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: "Windows Latest MSVC"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v3

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          
      - name: Install dependencies
        run: |
          choco install ninja cmake
          ninja --version
          cmake --version
          cmd "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          
      - name: Configure
        shell: bash
        run: |
          mkdir build
          mkdir instdir
          cmake \
            -S . \
            -B . \
            -DCMAKE_BUILD_TYPE="Debug" \
            -G "Visual Studio 16 2019"
      - name: Build
        shell: bash
        run: cmake --build .
      
      - name: Tmp
        run: ls
